### PR TITLE
Add dots and caps to evil-surround-tag-name-re

### PR DESCRIPTION
**Pull request by deviantfero**
I've tested this and it seems to work for my use case, this should take care of the issue I opened in #155, please advice if you see something wrong or some potentially breaking change.

thank you for creating this plugin :+1:

### CODE REVIEW

**Comment by ninrod** [comment]
Thank you for your contribution. Would you be able to add tests for this scenario?

it's really easy and this should help: https://github.com/emacs-evil/evil-surround#contributing

**Comment by deviantfero** [comment]
I've added some tests, please let me know if we need more :100:

**Comment by ninrod** [comment]
thank you. the tests are failing after the evil git clone. I'll have to take a look.

**Comment by deviantfero** [comment]
Weird which one seems to be failing? I ran the tests and they finished
successfully

**Comment by ninrod** [comment]
yes, the tests are passing on my terminal. they are failing on travis.

**Comment by deviantfero** [comment]
Is it a problem with Travis? it seems that it fails to find `evil` or something like that before actually running the tests

**Comment by ninrod** [comment]
Yes, it happened on my terminal too, but after the second make, it worked. It seems that the bootstrap step is flaky. I should be able to merge this soon anyway because the tests are actually passing. But I should take a closer look at this.

**Comment by deviantfero** [comment]
great :+1:, just call out if you need any more changes on my side

**Comment by ninrod** [comment]
@deviantfero, sorry for the wait time. I've already squashed and merged your commits. 

Again, thank you so much for your contribution.

**Comment by ninrod** [comment]
for reference, this is the commit: d210e1fc2cf1c2d095471cefa700a0d1703f4ab6

**Pull request closed without merging**
