### PR TITLE
Fix repeat when pair is determined by function

### LINKED ISSUE #125: tag and function surrounding repeat is broken
# repro steps: 

1. open any buffer and type some lines.
2. with the cursor in the first line, type `yss<pRET`.
3. now try to repeat the operation in the line below with the `.` operator.

You will see the following error message:

```txt
After 0 kbd macro iterations: evil-motion-range: Wrong type argument: characterp, -1
```

### PR DESCRIPTION
**Pull request by justbur**
Apparently when read-from-minibuffer is called in a function to read tags, the
information in this-command-keys is discarded. Introduce
evil-surround-read-from-minibuffer to record this information as well as the
input in the minibuffer.

There is probably a more elegant solution to recording repeat info in
evil-surround out there, but this will work for now.

Fixes #125

### CODE REVIEW

**Comment by ninrod** [comment]
Excelent work @justbur! Thank you very much. ❤️

**Comment by ninrod** [comment]
@justbur, just added some tests for your pull in #757ddb93c7fb95373e029bd8404e01e9ef958815. What do you think?

**Comment by justbur** [comment]
They look ok to me. Hopefully, they pass :)

**Comment by ninrod** [comment]
they passed! 🚀

**Pull request merged**
