### PR TITLE
Fix surrounding with a tag in a macro

### PR DESCRIPTION
**Pull request by jamesnvc**
Addresses #159

### CODE REVIEW

**Comment by jamesnvc** [comment]
The failing CI check seems to be building the docker image...

**Comment by ninrod** [comment]
@jamesnvc are you using `evil-surround` with your changes? I'll try to use this week besides running the tests to see if I find anything odd.

**Comment by ninrod** [comment]
Yes, I'm having trouble with travis integration for sometime now. Did not have the time to stop and see through the issue though.

**Comment by jamesnvc** [comment]
@ninrod yes, I'm using it with the changes now & it seems to be working okay. Thanks!

**Comment by ninrod** [comment]
@jamesnvc, I ran the tests and played around. everything seems to be running all right.

**Comment by ninrod** [comment]
@jamesnvc, actually, I've found a bug within your current PR. 

consider a buffer like this (point is on [*]) (I'm using evil/vim's qa instead of `C-x (`, but it's the same)

```txt
[f]oo
bar
baz
```

after `qaysetfoo>jq`, if I apply the macro on the `bar` line, it becomes: 

```txt
<foo>foo</foo>
<fooo>bar</fooo>
baz
```
notice the extra `o` on the foo tag. 

that does not happen if I drop the `j` from the macro recording. 

would you be able to fix this issue?

**Comment by jamesnvc** [comment]
Very puzzling; I can't seem to reproduce that issue when testing via `make emacs`. That was exactly my basic test case too, which makes it not working now extra confusing.

Does that consistently happen? I recall seeing something like that when I was initially trying to write the test cases, but it went away at some point.

**Comment by jamesnvc** [comment]
Looking at the code again, I'm not convinced that it actually needs the select-window stuff either. Removing it, making the function in the key map just be `(call-interactively #'self-insert-command) (exit-minibuffer)` also works. I wonder if the switch windows is what's causing the extra characters to be inserted some how?

**Comment by jamesnvc** [comment]
Hm! In the process of trying to write more tests to figure this out, I think I uncovered another issue with the tag-changing not working with repeat, even without my change here; I'll make another issue for that.

**Comment by ninrod** [comment]
@jamesnvc I think @tam5 commit 68f7033 which I've merged into master is the culprit. 
I do remember macros working perfectly in evil-surround and now they are behaving extremely lately. I've found that before 68f7033, everything works as expected marcro wise.

**Comment by tam5** [comment]
I'll try and look into it as well

**Comment by ninrod** [comment]
gentleman, I've uploaded a branch called `devel`, which is the combination of @jamesnvc PRs #160 and #162. I find that that these PRs combined solve the issue. I used `make emacs` to be sure to test in a neutral ground. 

Would gentleman  care to take the branch for a spin and report the results? thank you. 

excelent work by the way @jamesnvc. Impressive.

**Comment by ninrod** [comment]
We should be sure to add some tests to catch these macro use cases, if @jamesnvc didn't do that already.

**Comment by tam5** [comment]
checked out that branch, seems to work great! thanks guys!

**Comment by jamesnvc** [comment]
Thanks @ninrod ! My pleasure :smile: I added a tests in both of those branches that should cover the issues.

**Comment by ninrod** [comment]
Thank you gentleman. All issues related to macro usage seem to be taken care of, thank you @jamesnvc and @tam5

**Pull request merged**
