### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by edkolev**

### CODE REVIEW

**Comment by edkolev** [comment]
Hi, this PR adds make-based testing "framework" and a few initial tests.

the evil-surround-test.el files contains some copy-pasted code from evil's evil-tests.el file to make writing tests easier. For example, the helper function `evil-test-buffer` is defined in the copy-pasted code.

I don't really like this copy-pasting. Maybe it would be better to make a new `evil-test-helpers` Melpa package from the evil-tests.el file (part of the evil repo) and just require it here. But for now I think it's better to get some tests, and then optimise and polish.

Let me know if the PR can be improved :)

To run the tests: 
1. `make update` - this will install dependencies, only `evil` in this case; run this once only
2. `make test` - run the ert tests

**Comment by edkolev** [comment]
Also, `make compile` will compile to byte code, and, more importantly, show any compile warnings. BTW There's one warning now:
```
In evil-surround-trim-whitespace-from-range:
evil-surround.el:145:17:Warning: looking-back called with 1 argument, but
    requires 2-3
```

**Comment by ninrod** [comment]
@edkolev awesome work! 

by the way just out of curiosity, there's another competing test framework for emacs I keep hearing about: buttercup. What test framework do you use in your emacs packages? is ERT like the de facto standard?

thanks!

**Comment by ninrod** [comment]
@edkolev, would  you like to have push access to master on evil-surround?

**Comment by edkolev** [comment]
Sure, push access would be much appreciated :)

I use only ERT - I checked a few high-traffic emacs packages (projectile, swiper, evil, and a few others I don't remember right now) all of which were using ERT and some of them where using Cask. I just went ahead and used ERT because these packages were using it. I haven't played enough with Cask, but I didn't find a good enough reason to use it.

**Pull request merged**
