### PR TITLE
Fix yss behavior with visual-line-mode

### PR DESCRIPTION
**Pull request by MintSoup**
This PR fixes my recently submitted issue, #173

### CODE REVIEW

**Comment by MintSoup** [comment]
Note that this way it "ignores" visual line mode and surrounds the real line, not the visual line. If it should surround only the visual line, let me know and I'll make the changes. IMO it would be better to make this depend on `evil-respect-visual-line-mode`.

**Comment by ninrod** [comment]
@MintSoup , thank you for your contribution.

Can you write a test for this scenario?

**Comment by MintSoup** [comment]
@ninrod What do you mean by a test? Could you please elaborate?

**Comment by ninrod** [comment]
Yes @MintSoup  we have a fairly complete test suite [here](https://github.com/emacs-evil/evil-surround/blob/master/test/evil-surround-test.el)

The instructions are [here](https://github.com/emacs-evil/evil-surround#contributing)

**Comment by MintSoup** [comment]
This is what I came up with:

```
  (ert-info ("compatibility with visual line mode")
    (evil-test-buffer
    :visual-start nil
    :visual-end nil
    "     one two three\nfour five"
    (turn-on-evil-surround-mode)
    (turn-on-visual-line-mode)
    ("yssb")
    "     (one two three)\nfour five"))
```
However, it seems that the test passes even without my patch. This is very weird, I've been trying for the past day but I can't get the test to replicate the behavior of the plugin normally. Could you please have a look?

**Comment by MintSoup** [comment]
@ninrod By the way, I'm sure you can tell from my change that the problem is that `type` is `screen-line` instead of `line` whenever visual line mode is enabled, which caused it to fallback to the default condition. This is purely speculation, but maybe the test doesn't fail because we need a real display with a certain width for `type` to be `screen-line`, since `visual-line-mode` only makes sense on visible text anyway?

**Comment by MintSoup** [comment]
Also just made it respect `evil-respect-visual-line-mode`, so now `yss` will now wrap the visual line only if `evil-respect-visual-line-mode` is set.

**Comment by ninrod** [comment]
> @ninrod By the way, I'm sure you can tell from my change that the problem is that type is screen-line instead of line whenever visual line mode is enabled, which caused it to fallback to the default condition. This is purely speculation, but maybe the test doesn't fail because we need a real display with a certain width for type to be screen-line, since visual-line-mode only makes sense on visible text anyway?

Hmm, I think you are onto something here, but it is way above my pay grade.

**Comment by MintSoup** [comment]
@ninrod Either way, from my testing the patch works fine. Is there anything else to do before we can merge?

**Comment by ninrod** [comment]
> @ninrod Either way, from my testing the patch works fine. Is there anything else to do before we can merge?

Yes, If we cannot write a test for this, I have to reproduce the issue locally.

**Comment by MintSoup** [comment]
@ninrod Ok then, let me know when you're done : )

**Comment by ninrod** [comment]
fixed in https://github.com/emacs-evil/evil-surround/commit/3bd73794ee5a760118042584ef74e2b6fb2a1e06

**Pull request closed without merging**
