### PR TITLE
use the `inherit-input-method` argument for read-char

### PR DESCRIPTION
**Pull request by willghatch**
Supercedes #114 -- this one doesn't break `.`.

### CODE REVIEW

**Comment by ninrod** [comment]
Ok. Can you write a test so we can confirm this?

**Comment by willghatch** [comment]
Done.  Sorry, I'm regrettably unfamiliar with testing methods in emacs, and I lately only write elisp when I have a problem that I want fixed, so I haven't gotten up to speed with it and it isn't my first thought to add tests to elisp projects.  But it was pretty easy to figure out your test file.

**Comment by ninrod** [comment]
thanks @willghatch. Will check your pr out carefully when I find some time.

**Comment by ninrod** [comment]
@willghatch, If I understand correctly, your pull tries to fix issues when working with UTF-8 characters comprised by more than 1 byte in lenght, right? 

What do you think about exercising this scenario with a test case?

**Comment by willghatch** [comment]
I'm generally good with that.  But I'm not entirely sure it will behave quite the same as actually reading the input from a terminal, and (more immediately impeding) when I use such unicode characters in the input strings of the test forms I get an error complaining about something not being a character.  Maybe I'll get it working tomorrow.

**Comment by willghatch** [comment]
Also, I'd like to note that if we get the repeat stuff fixed in evil core, you should revert the revert that used `(interactive "<C>")` and `evil-read-key`, because that patch was simply a better version of this one that suffered from a bug in evil itself.  Though you should add the commit that tests the repeat functionality.

**Comment by ninrod** [comment]
> Also, I'd like to note that if we get the repeat stuff fixed in evil core, you should revert the revert that used (interactive "<C>") and evil-read-key, because that patch was simply a better version of this one that suffered from a bug in evil itself. Though you should add the commit that tests the repeat functionality.

I see, interesting.

**Comment by willghatch** [comment]
In retrospect, anyway. I didn't know about that other patch when I submitted mine, but having read it, I now see that it fixes my original issue plus others. Its only fault was that it tripped up this other bug in evil-repeat.

On June 26, 2017 6:48:58 PM MDT, Filipe Silva <notifications@github.com> wrote:
>> Also, I'd like to note that if we get the repeat stuff fixed in evil
>core, you should revert the revert that used (interactive "<C>") and
>evil-read-key, because that patch was simply a better version of this
>one that suffered from a bug in evil itself. Though you should add the
>commit that tests the repeat functionality.
>
>I see, interesting.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/emacs-evil/evil-surround/pull/115#issuecomment-311221283

-- 
Sent from my pocket computer.  Please excuse the lint.

**Comment by ninrod** [comment]
@willghatch, what do you suggest?

**Comment by willghatch** [comment]
Actually, I'm suggesting just using #81 as is, which was correct, once the bug in evil that causes the problem is fixed.  It fixes a couple of things that this patch misses.

**Comment by ninrod** [comment]
all right. On the other hand, your patch has tests. I'd still love a test in the lines described [here](https://github.com/emacs-evil/evil-surround/pull/115#issuecomment-311213557)

**Comment by willghatch** [comment]
You can cherry pick the commit with the test.  I tried to write a test to exercise the unicode stuff, but couldn't seem to get it to work.  Maybe I'll try again later.

**Comment by ninrod** [comment]
closed because of [this](https://github.com/emacs-evil/evil-surround/issues/36#issuecomment-319511098) rationale.

**Pull request closed without merging**
