### PR TITLE
When motion is 'word' and evil-want-change-word-to-end is t, behave like 'ce', not 'cw'

### PR DESCRIPTION
**Pull request by edkolev**
This seems like a simple solution to #117 

@ninrod let me know if you think this approach is OK, and I'll add tests.

#120 should probably be merged first though, so we get better test coverage when this is merged.

### CODE REVIEW

**Comment by ninrod** [comment]
@edkolev, yes, I think it is a nice approach. Please let's tests to this pull!

I've just merged #120

**Comment by edkolev** [comment]
While adding tests, I found this issue:
- with `hello [w]orld`
- `ysw'`
- results in `hello 'worl'd`, which is incorrect

Another issue:
- with `[h]ello     world`
- `ysw'`
- results in `'hello  ' world`, which again is wrong

I'll let you know if I get this sorted.

**Comment by ninrod** [comment]
@edkolev, awesome that the test discipline helped to catch that.

**Comment by edkolev** [comment]
Closing, see #122

**Pull request closed without merging**
